# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    reviewers: ["spinute"]
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2

  - package-ecosystem: "gomod"
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    reviewers:  ["spinute"]
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
